### ISSUE TITLE
a little wish

### ISSUE THREAD

**Issue by Pryan1kk** [rhydiaan/NicerTeleporters#6]
Can you make it possible to teleport "radar booster" back?

**Comment by rhydiaan** [comment]
sorry only now seeing this, I'll try and get it done tonight

**Comment by rhydiaan** [comment]
actually as I'm on a new system my whole visual studio is playing up so even this small change is throwing 90 errors. I'll try and get it working some time next week, sorry for the delay.

**Comment by Pryan1kk** [comment]
Great, I'll be waiting.

**Comment by rhydiaan** [comment]
Update done. Can be found in the releases page or through thunderstore :)

**Comment by Pryan1kk** [comment]
(noticed update)

Oh, that's not what I meant, I wanted it to be able to teleport back when it's deployed (select it in the cameras and teleport it) but that could work great too

**Comment by Pryan1kk** [comment]
you did great work btw

**Comment by Pryan1kk** [comment]
if you're tired, you don't have to add anything, I'm happy with that too

**Comment by rhydiaan** [comment]
Ah okay yeah I misunderstood, with how the teleport feature works right now I'm pretty sure I'd have to do a rewrite how the teleporter works in order to do this (which is a bit more advanced than I'm capable of at the moment) because the player and the radar boosters are separate entities and don't behave the same. I'm sorry and I know this probably isn't what you were hoping for but hopefully this small change at least makes it a bit better for you and your friends :)

**Comment by Pryan1kk** [comment]
<3
